version: '3.8'

services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: url_shortener_db
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d

  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm run dev'
    environment:
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: url_shortener_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  vite:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "5173:5173"
    # volumes:
    #   - ./frontend:/app/frontend

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vite
      - backend

